version: '3.8'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_broker_container
    volumes:
      - my-vol:/app/myapp
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  mysql:
    image: mysql:oracle
    container_name: mysql_db_container
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: codeguru
      MYSQL_PASSWORD: CodeGuru96
      MYSQL_DATABASE: courses
    command: --default-authentication-plugin=mysql_native_password

volumes:
  my-vol:
  mysql_data:
